[<img alt="LOGO" src="http://www.gqylpy.com/static/img/favicon.ico" height="21" width="21"/>](http://www.gqylpy.com)
[![Version](https://img.shields.io/pypi/v/gqylpy_exception)](https://pypi.org/project/gqylpy_exception/)
[![Python Versions](https://img.shields.io/pypi/pyversions/gqylpy_exception)](https://pypi.org/project/gqylpy_exception)
[![License](https://img.shields.io/pypi/l/gqylpy_exception)](https://github.com/gqylpy/gqylpy-exception/blob/master/LICENSE)
[![Downloads](https://pepy.tech/badge/gqylpy_exception/month)](https://pepy.tech/project/gqylpy_exception)

# gqylpy-exception


> 在执行`raise`语句时直接创建异常，无需事先定义异常类，方便快捷。例如，你想抛出一个名为`NotUnderstandError`的异常，导入`import gqylpy_exception as ge`后执行`raise ge.NotUnderstandError`即可。


<kbd>pip3 install gqylpy_exception</kbd>
